// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://ehnynvfzicdijvmglezy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVobnludmZ6aWNkaWp2bWdsZXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0Njc0NDYsImV4cCI6MjA2ODA0MzQ0Nn0.lq5kJ3I93sV9lyE2HYygRTbZhIRMT7skC-7XQXlLj0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
