// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvhmqhfiwlpadhwbxmbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2aG1xaGZpd2xwYWRod2J4bWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzI5MDAsImV4cCI6MjA3MDEwODkwMH0.c7_xq1BuMER6oGX6qYhZHrVPPiyUjix8ySAd5aS9v04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});