// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddblrsgadetiwoijleqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkYmxyc2dhZGV0aXdvaWpsZXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTE3NTcsImV4cCI6MjA2OTI2Nzc1N30.x0Ia3FC7jEH9AKYKGwc65T0B_1YhyKSCRZzC6teYweQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});